spring:
  application:
    name: cashcard


server:
  port: 8090


paypal:
  client-id: ART-XE_FbhAzETbYNX6mqA7grhK4vBRqVmnBaaJpiIjFZhGNStAp_jf2ajXh4u9243SoWIQhG57TDXzX
  client-secret: EF-0tG68Oj0xWgI8YnxjoGq5rtoCruoqgfhvM5K1ovTO3YchPpXwbeCk1t_-S7t_sC_iJ9VyDghjfJH_
  mode: sandbox #Use #sanbox for texting and 'live' for Production


